### ISSUE TITLE
Preguntas para Nodeshool

### ISSUE THREAD

**Issue by pricco** [latamjs/eventos#1]
@a0viedo Podrías compartir el set de preguntas para nodeschool que estas usando en ti.to?

**Comment by a0viedo** [comment]
@pricco claro! y esto seguro lo debamos subir en alguno de los repos.

- ¿Qué experiencia tenés con JavaScript?
  - Cero
  - Básica
  - Intermedia
  - Avanzada
- ¿Qué experiencia tenés con Node.js?
  - Cero
  - Básica
  - Intermedia
  - Avanzada
- ¿Cómo te enteraste de NodeSchool (Chapter)?

**Comment by bevacqua** [comment]
Les pido si pueden mover esta discusión a wg-comunidades así podemos limpiar un poco la organización
