### ISSUE TITLE
Define (flexible) JSON format for events

### ISSUE THREAD

**Issue by bevacqua** [latamjs/eventos#11]
La idea es definir un formato en JSON para el listado de eventos, de forma tal que podamos eventualmente mostrar esta información de varias formas.

- En un mapa con pines y un popup con información sobre el evento, ala NodeSchool
- En un listado como está actualmente en el README
- En la web una breve mención de los eventos que están sucendiendo dentro del próximo mes

**Comment by eafelix** [comment]
+1

**Comment by bevacqua** [comment]
A grandes rasgos. Tiren campos que les parezca que falten

```js
[{
  "name": "BeerJS BA", // nombre del evento,
  "description": "BeerJS en Buenos Aires es una amalgama de ebrios, JavaScripters, y **JavaScripters ebrios**.", // descripción en markdown
  "type": "meetup", // one of "meetup", "conference", ...?, "other"
  "events": [{
    "date": "2015-05-04T22:00:00.000Z", // fecha del evento
    "name": "Primer BeerJS Buenos Aires",
    "province": "Buenos Aires", // provincia o estado
    "country": "Argentina", // país del evento, o "remote"
    "geo": { // latitud y longitud para geolocalización
      "lat" : 37.4224764,
      "lng" : -122.0842499
    }
  }]
}]
```

**Comment by bevacqua** [comment]
Cuanto antes definamos esto más fácil va a ser el tema de la web. Idealmente podríamos usar algo como [sheetsee](https://github.com/jlord/sheetsee.js/) o cualquier otra cosa que nos deje ser no-backend.

**Comment by jeduan** [comment]
creo que necesitamos URL de tickets, e idealmente una forma de definir eventos recurrentes. Algo que hice también fue tomar eventos directamente de la API de meetup.com.

**Comment by leoasis** [comment]
+1! Agrego algunos campos:

* URL donde esta especificamente hosteado el evento (meetup.com por ejemplo)
* Tipo de asistencia (presencial o remota por HO o algo similar)
* Capacidad maxima del evento (?)
* Nombre del/los hosts

**Comment by pricco** [comment]
+1 @bevacqua / @leoasis 

Agrego otros (podrían ser por comunidad o evento)
* `twitterHashtag`
* `twitterHandle`
* `urls [{type?, name, url}, ...]` // A veces tenemos varias urls por evento de diferente tipo.

**Comment by bevacqua** [comment]
Evitemos cosas muy especificas a una plataforma, estoy de acuerdo con todo lo q tiraron, agregandolo al formato que definí arriba. Lo que es capacidad o hosts o demás cosas especificas evité incluirlas porque se me hace que es info que tiene que estar en la página de los eventos, info que nadie va a querer completar para latamjs (o que vamos a terminar completando nosotros), y probablemente en la mayoría de use cases ni tengamos donde ponerla (lista con breve reseña de eventos, mapa con locaciones y un popup con info del evento, etc). Lo del hashtag me gusta en la teoría pero *all of the above*

```js
[{
  "name": "BeerJS BA", // nombre del evento,
  "description": "BeerJS en Buenos Aires es una amalgama de ebrios, JavaScripters, y **JavaScripters ebrios**.", // descripción en markdown
  "type": "meetup", // uno de "meetup", "conference", ...?, "other"
  "province": "Buenos Aires", // provincia o estado del evento para catalogar, null si es "remote"
  "country": "Argentina", // país del evento, o "remote", para catalogar
  "events": [{
    "date": "2015-05-04T22:00:00.000Z", // fecha del evento
    "name": "Primer BeerJS Buenos Aires",
    "province": "Buenos Aires", // provincia o estado, null si el evento es "remote"
    "country": "Argentina", // país del evento, o "remote"
    "location": "Puerta Roja, San Telmo", // lugar del evento user-friendly
    "geo": { // latitud y longitud para geolocalización, null si el evento es "remote"
      "lat" : 37.4224764,
      "lng" : -122.0842499
    },
    "links": [{ // links específicos a un evento
      "type": "landing", // uno de "landing", "tickets", "other"
      "href": "www.meetup.com/Beer-js-Buenos-Aires/events/221997608/", // el link
      "text": "meetup.com/beer-js-buenos-aires" // descripción, opcional
    }]
  }],
  "links": [{ // links generales de la meetup
    "type": "social", // uno de "landing", "social", "other"
    "href": "https://twitter.com/beerjsba", // el link
    "text": "@beerjsba" // descripción, opcional
  }]
}]
```

**Comment by bevacqua** [comment]
Sigue en https://github.com/latamjs/gt-devel/issues/1
