### ISSUE TITLE
[propuesta] Separar los eventos por país.

### ISSUE THREAD

**Issue by pazguille** [latamjs/eventos#13]
Hola,

Creo que estaría bueno separar los eventos por país para que estén más ordenados y sea mucho más fácil buscar.

Al igual que está en https://github.com/latamjs/eventos/blob/master/COMUNIDAD.md 
Qué les parece?

**Comment by eafelix** [comment]
Concuerdo totalmente @pazguille , una cosa es el cronograma de eventos de cada pais y otra es el listado de comunidades.   
Justo aca comentaba el mismo tema jajajajajaj. 
 
https://github.com/latamjs/eventos/issues/14

**Comment by bevacqua** [comment]
+1
