### ISSUE TITLE
Usar comunidades como README.md principal en esta seccion

### ISSUE THREAD

**Issue by eafelix** [latamjs/eventos#14]
Pensaba que, a lo mejor, es mas importante dejar el listado completo de comunidades en otro repo para administrarlo y tengan los chicos una forma mas directa y visible la búsqueda de comunidades, y en este dejar solamente el listado según el pais los eventos por venir. 

Que opinan?

**Comment by pazguille** [comment]
+1

**Comment by bevacqua** [comment]
Opino que lo que venimos haciendo aca esta bien para recolectar info pero deberiamos moverlo a formato json y publicarlo en la web. Se puede autogenerar un readme tambien usando ese json.

**Comment by eafelix** [comment]
estoy de acuerdo, en tal caso podemos meterlo en cada pais del json o hacerlo por separdo, pero como decis, en ese formato,de la forma de como a vos te apresca

**Comment by eafelix** [comment]
Acá cree el repo donde migrar todo lo relacionado a las comunidades existentes y la promoción de las mismas para dejar en este repo info de los eventos venideros y los recientes pasados. 

https://github.com/latamjs/comunidades

Después de la definición de los WG , dependiendo como queden, volvemos a organizarlos, me parece que de esta forma por ahora es funcional hasta tener esa resolución.
que opinan?
