### ISSUE TITLE
agregar eventos para Chile

### ISSUE THREAD

**Issue by gbelmm** [latamjs/eventos#8]
angularjs
tw: @angularjschile
web: www.angularjs.cl
g+:  https://plus.google.com/u/0/communities/115823399984742959232

google dev chile:
web: gdgsantiago.cl
g+: https://plus.google.com/u/0/communities/112127889517860317863

**Comment by eafelix** [comment]
@gbelmm como estas? 

Queres crearte el pull request para mergearlos a https://github.com/latamjs/eventos/blob/master/COMUNIDAD.md   ?

**Comment by gbelmm** [comment]
ok
